-- Unkle Funk — WIP Q&A schema
-- Paste this whole file into Supabase → SQL Editor → New query → Run.

create table if not exists wip_feedback (
  id          bigint generated by default as identity primary key,
  track_slug  text not null,                    -- matches data-track on each card
  nickname    text default 'Anonymous',
  message     text not null,
  created_at  timestamptz not null default now()
);

alter table wip_feedback enable row level security;

-- Anyone can read comments (public site display)
create policy "public can read feedback"
  on wip_feedback for select
  using (true);

-- Anyone can post a comment, but only within sane limits
-- (message length + nickname length enforced here, not just client-side)
create policy "public can insert feedback"
  on wip_feedback for insert
  with check (
    char_length(message) between 1 and 500
    and char_length(nickname) <= 40
  );

-- No update/delete policy exists for the public role, so anon key
-- can never edit or remove a comment once posted — moderation only
-- happens from the Supabase dashboard (Table Editor) with your login.

create index if not exists wip_feedback_track_idx on wip_feedback (track_slug, created_at desc);
