// Sketch: "Bronzeville After Dark"
// Vibe: Late-night South Side groove, warm, soulful, and swinging. Philly soul meets Chicago jack.
// BPM: 129 | Key: F Minor | Bars: 16 | Humanize: loose
//
// Generated by Unkle Funk Dream Engine — 2026-10-05

import type { NoteDescription } from "@ableton-extensions/sdk";
import { humanize } from "../humanizer.js";

export const SKETCH_NAME = "Bronzeville After Dark";
export const BPM = 129;
export const BARS = 16;
export const KEY = "F Minor";

// Trigger note for all drum tracks (separate-track setup, C3 = 48)
const TRIGGER = 48;

// Bass pitches in F minor (C1-C2 register)
const F1 = 29;
const Ab1 = 32;
const C2 = 36;
const Eb2 = 39;

// Chord pitches: Fm7 (Ab3, C4, Eb4, G4)
const Ab3 = 56;
const C4 = 60;
const Eb4 = 63;
const G4 = 67;

// ─── Kick: 4/4 with a syncopated 16th shuffle ──────────────────────────────
export function kickNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Standard 4/4
    for (let i = 0; i < 4; i++) {
      notes.push({ pitch: TRIGGER, startTime: barStart + i, duration: 0.3, velocity: 110 });
    }
    // The "Shuffle Kick" — an extra kick on the 16th note before beat 3
    if (bar % 2 === 0) {
      notes.push({ pitch: TRIGGER, startTime: barStart + 2.75, duration: 0.2, velocity: 85 });
    }
  }
  return humanize(notes, BPM, "loose");
}

// ─── Snare: Rimshot on 2 and 4 with ghost notes ────────────────────────────
export function snareNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Main Rim
    notes.push({ pitch: TRIGGER, startTime: barStart + 1, duration: 0.15, velocity: 100 });
    notes.push({ pitch: TRIGGER, startTime: barStart + 3, duration: 0.15, velocity: 100 });
    
    // Ghost note on the "and" of 4 every 4 bars
    if (bar % 4 === 3) {
      notes.push({ pitch: TRIGGER, startTime: barStart + 3.5, duration: 0.1, velocity: 50 });
    }
  }
  return humanize(notes, BPM, "loose");
}

// ─── Hi-Hats: Driving 16ths with 8th note accent ───────────────────────────
export function hatNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    for (let i = 0; i < 16; i++) {
      const startTime = barStart + (i * 0.25);
      // Accent the 8th note "and" positions (0.5, 1.5, 2.5, 3.5)
      const isAccent = i % 2 !== 0;
      notes.push({
        pitch: TRIGGER,
        startTime: startTime,
        duration: isAccent ? 0.2 : 0.1,
        velocity: isAccent ? 85 : 65
      });
    }
  }
  return humanize(notes, BPM, "loose");
}

// ─── Percs: Bongo/Shaker syncopation ───────────────────────────────────────
export function percNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  const pattern = [
    { beat: 0.75, vel: 70, dur: 0.1 },
    { beat: 1.3,  vel: 85, dur: 0.1 },
    { beat: 2.5,  vel: 60, dur: 0.1 },
    { beat: 3.2,  vel: 75, dur: 0.1 },
  ];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    pattern.forEach(p => {
      notes.push({ pitch: TRIGGER, startTime: barStart + p.beat, duration: p.dur, velocity: p.vel });
    });
  }
  return humanize(notes, BPM, "loose");
}

// ─── Bass: Syncopated F Minor Groove ───────────────────────────────────────
export function bassNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  // A rhythmic, bouncy pattern
  const pattern: NoteDescription[] = [
    // Bar 1
    { pitch: F1, startTime: 0, duration: 0.5, velocity: 105 },
    { pitch: F1, startTime: 0.75, duration: 0.5, velocity: 90 },
    { pitch: Ab1, startTime: 2, duration: 0.5, velocity: 95 },
    { pitch: C2, startTime: 3, duration: 0.8, velocity: 100 },
    // Bar 2
    { pitch: Eb2, startTime: 4.5, duration: 0.5, velocity: 90 },
    { pitch: F1, startTime: 5.5, duration: 1.5, velocity: 105 },
    // Bar 3
    { pitch: Ab1, startTime: 8, duration: 0.5, velocity: 95 },
    { pitch: C2, startTime: 9.5, duration: 0.5, velocity: 95 },
    { pitch: F1, startTime: 11, duration: 1, velocity: 100 },
    // Bar 4 (Turnaround)
    { pitch: Eb2, startTime: 12, duration: 0.5, velocity: 90 },
    { pitch: C2, startTime: 13, duration: 0.5, velocity: 90 },
    { pitch: Ab1, startTime: 14, duration: 0.5, velocity: 90 },
    { pitch: F1, startTime: 15, duration: 1, velocity: 110 },
  ];

  // Loop pattern for 16 bars (using first 4 bars as template)
  for (let loop = 0; loop < 4; loop++) {
    pattern.forEach(p => {
      notes.push({ ...p, startTime: p.startTime + (loop * 16) });
    });
  }

  return humanize(notes, BPM, "loose");
}

// ─── Chords: Soulful Fm7 stabs ────────────────────────────────────────────
export function chordNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  const Fm7 = [Ab3, C4, Eb4, G4];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Stab on the "and" of 1 and the "and" of 3
    const stabTimes = [0.5, 2.5];
    
    // Only play stabs on even bars to keep it spacious
    if (bar % 2 === 0) {
      stabTimes.forEach(t => {
        Fm7.forEach(pitch => {
          notes.push({ pitch, startTime: barStart + t, duration: 0.4, velocity: 75 });
        });
      });
    }
  }
  return humanize(notes, BPM, "loose");
}