// Sketch: "Bronzeville Midnight Groove"
// Vibe: Warm, humid, soulful Chicago house. Deep textures and organic movement.
// BPM: 122 | Key: F Minor | Bars: 16 | Humanize: loose
//
// Generated by Unkle Funk Dream Engine — 2026-10-03

import type { NoteDescription } from "@ableton-extensions/sdk";
import { humanize } from "../humanizer.js";

export const SKETCH_NAME = "Bronzeville Midnight Groove";
export const BPM = 122;
export const BARS = 16;
export const KEY = "F Minor";

// Trigger note for all drum tracks (separate-track setup, C3 = 48)
const TRIGGER = 48;

// Bass pitches in F minor (MIDI, C2 register)
const F1  = 29;
const Ab1 = 32;
const C2  = 36;
const Eb2 = 39;
const F2  = 41;

// Chord pitches in F minor (MIDI, higher register 55-76)
const Ab4 = 56;
const C5  = 60;
const Eb5 = 63;
const G5  = 67;

// ─── Kick: Driving 4/4 with a slight swing feel ──────────────────────────────
export function kickNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    for (let beat = 0; beat < 4; beat++) {
      notes.push({ pitch: TRIGGER, startTime: barStart + beat, duration: 0.4, velocity: 110 });
    }
  }
  return humanize(notes, BPM, "loose");
}

// ─── Snare: Strong 2 and 4 with syncopated ghost notes ──────────────────────
export function snareNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Main backbeat
    notes.push({ pitch: TRIGGER, startTime: barStart + 1, duration: 0.25, velocity: 100 });
    notes.push({ pitch: TRIGGER, startTime: barStart + 3, duration: 0.25, velocity: 100 });

    // Ghost note on the 'and' of 4 to add shuffle
    notes.push({ pitch: TRIGGER, startTime: barStart + 3.5, duration: 0.1, velocity: 45 });
  }
  return humanize(notes, BPM, "loose");
}

// ─── Hi-Hats: Constant 16th note shuffle ────────────────────────────────────
export function hatNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    for (let i = 0; i < 16; i++) {
      const startTime = barStart + (i * 0.25);
      // Accent every 4th 16th note (the 8th notes)
      const isAccent = i % 2 === 1;
      notes.push({
        pitch: TRIGGER,
        startTime: startTime,
        duration: isAccent ? 0.2 : 0.1,
        velocity: isAccent ? 85 : 60
      });
    }
  }
  return humanize(notes, BPM, "loose");
}

// ─── Percs: Syncopated woodblock/shaker pattern ─────────────────────────────
export function percNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  // Pattern: 1.3, 2.3, 3.3, 4.3
  const pattern = [0.75, 1.75, 2.75, 3.75];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    pattern.forEach(offset => {
      notes.push({ pitch: TRIGGER, startTime: barStart + offset, duration: 0.15, velocity: 75 });
    });
  }
  return humanize(notes, BPM, "loose");
}

// ─── Bass: Deep F minor syncopated line ─────────────────────────────────────
export function bassNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    
    // Root on the 1
    notes.push({ pitch: F1, startTime: barStart, duration: 0.8, velocity: 95 });
    
    // Syncopated movement
    if (bar % 2 === 0) {
      notes.push({ pitch: Ab1, startTime: barStart + 1.5, duration: 0.4, velocity: 85 });
      notes.push({ pitch: C2,  startTime: barStart + 2.75, duration: 0.5, velocity: 88 });
    } else {
      notes.push({ pitch: Eb2, startTime: barStart + 2, duration: 0.6, velocity: 82 });
      notes.push({ pitch: F1,  startTime: barStart + 3.5, duration: 0.4, velocity: 90 });
    }
  }
  return humanize(notes, BPM, "loose");
}

// ─── Chords: Soulful Fm7 stabs ──────────────────────────────────────────────
export function chordNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  const Fm7 = [Ab4, C5, Eb5, G5];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Stab on the 'and' of 2 and the 'and' of 4
    const stabs = [1.5, 3.5];
    
    stabs.forEach(offset => {
      // Only stab on even bars to create space/tension
      if (bar % 2 === 0) {
        Fm7.forEach(p => {
          notes.push({ pitch: p, startTime: barStart + offset, duration: 0.5, velocity: 70 });
        });
      }
    });
  }
  return humanize(notes, BPM, "loose");
}
