// Sketch: "Slow Burn on State Street"
// Vibe: Late-night Chicago deep house, minimal and spacious. Larry Heard would nod.
// BPM: 123 | Key: C Minor | Bars: 8 | Humanize: tight
//
// Generated by Unkle Funk Dream Engine — 2026-06-04

import type { NoteDescription } from "@ableton-extensions/sdk";
import { humanize } from "../humanizer.js";

export const SKETCH_NAME = "Slow Burn on State Street";
export const BPM = 123;
export const BARS = 8;
export const KEY = "C Minor";

// Trigger note for all drum tracks (separate-track setup, C3 = 48)
const TRIGGER = 48;
const BEATS = BARS * 4; // 32 beats total

// Bass pitches in C minor (MIDI, C2 register)
const C2  = 36;
const G1  = 31;
const Eb2 = 39;
const Bb1 = 34;

// Chord pitches: Cm = C4, Eb4, G4
const C4  = 60;
const Eb4 = 63;
const G4  = 67;

// ─── Kick: standard 4/4, with a syncopated "Chicago push" every 4 bars ────────
export function kickNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Downbeat kick every bar
    notes.push({ pitch: TRIGGER, startTime: barStart, duration: 0.3, velocity: 105 });
    // "Chicago push" — an extra kick on beat 2.5 every even bar for forward momentum
    if (bar % 2 === 0) {
      notes.push({ pitch: TRIGGER, startTime: barStart + 2.5, duration: 0.2, velocity: 88 });
    }
  }
  return humanize(notes, BPM, "tight");
}

// ─── Snare: 2-and-4 with ghost note on beat 1.75 of odd bars ────────────────
export function snareNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Main snare on beat 2
    notes.push({ pitch: TRIGGER, startTime: barStart + 2, duration: 0.2, velocity: 90 });
    // Ghost note just before beat 2 on odd bars
    if (bar % 2 === 1) {
      notes.push({ pitch: TRIGGER, startTime: barStart + 1.75, duration: 0.15, velocity: 38 });
    }
  }
  return humanize(notes, BPM, "tight");
}

// ─── Hi-Hats: off-beat 8ths with open hat on the "and" of beat 2 ─────────────
export function hatNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  const offBeats = [0.5, 1.5, 2.5, 3.5]; // 8th note off-beats only (very deep house)
  const openHatBeat = 2.5; // "and of 2" — classic house breathe

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    offBeats.forEach((beat, i) => {
      const isOpenHat = beat === openHatBeat && bar % 4 === 0;
      notes.push({
        pitch: TRIGGER,
        startTime: barStart + beat,
        duration: isOpenHat ? 0.7 : 0.2,
        velocity: i % 2 === 0 ? 75 : 85, // alternating velocity for swing feel
      });
    });
  }
  return humanize(notes, BPM, "tight");
}

// ─── Percs: rolling conga pattern — Afro house influence ─────────────────────
export function percNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  // Rolling conga feel: light on 1, accented on 1.5, ghost on 3, accent on 3.5
  const pattern = [
    { beat: 1,    vel: 55, dur: 0.2 },
    { beat: 1.5,  vel: 70, dur: 0.15 },
    { beat: 3,    vel: 50, dur: 0.2 },
    { beat: 3.5,  vel: 68, dur: 0.15 },
  ];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Rest every 4th bar to let the groove breathe
    if (bar % 4 === 3) continue;
    pattern.forEach(({ beat, vel, dur }) => {
      notes.push({ pitch: TRIGGER, startTime: barStart + beat, duration: dur, velocity: vel });
    });
  }
  return humanize(notes, BPM, "loose"); // looser humanization on percs for organic feel
}

// ─── Bass: C minor root-walking pattern ──────────────────────────────────────
export function bassNotes(): NoteDescription[] {
  // 8-bar bass line in C minor — minimal, hypnotic
  const pattern: NoteDescription[] = [
    // Bar 1: C2 whole bar
    { pitch: C2,  startTime: 0,    duration: 3.5, velocity: 92 },
    // Bar 2: C2 short, G1 walking down
    { pitch: C2,  startTime: 4,    duration: 0.5, velocity: 88 },
    { pitch: G1,  startTime: 4.5,  duration: 3.5, velocity: 85 },
    // Bar 3: Eb2 tonal color
    { pitch: Eb2, startTime: 8,    duration: 3.75, velocity: 90 },
    // Bar 4: C2 whole bar (return home)
    { pitch: C2,  startTime: 12,   duration: 3.5, velocity: 92 },
    // Bar 5: C2 whole bar
    { pitch: C2,  startTime: 16,   duration: 3.5, velocity: 90 },
    // Bar 6: Bb1 → G1 (descending tension)
    { pitch: Bb1, startTime: 20,   duration: 1.5, velocity: 85 },
    { pitch: G1,  startTime: 21.5, duration: 2.5, velocity: 88 },
    // Bar 7: Eb2
    { pitch: Eb2, startTime: 24,   duration: 3.75, velocity: 90 },
    // Bar 8: G1 → C2 (tension and resolution)
    { pitch: G1,  startTime: 28,   duration: 2,   velocity: 85 },
    { pitch: C2,  startTime: 30,   duration: 2,   velocity: 95 },
  ];
  return humanize(pattern, BPM, "tight");
}

// ─── Chords: sparse Cm stabs on beat 2 — signature deep house placement ───────
export function chordNotes(): NoteDescription[] {
  const Cm = [C4, Eb4, G4];
  const notes: NoteDescription[] = [];

  // Stab pattern: bars 1, 2, 3, 5, 6 — rest on bars 4, 7, 8 for space
  const stabBars = [0, 1, 2, 4, 5];
  stabBars.forEach((bar) => {
    const barStart = bar * 4;
    Cm.forEach((pitch) => {
      notes.push({ pitch, startTime: barStart + 2, duration: 0.35, velocity: 72 });
    });
    // Second stab on beat 3.5 for bars 0 and 4 (call-and-response)
    if (bar === 0 || bar === 4) {
      Cm.forEach((pitch) => {
        notes.push({ pitch, startTime: barStart + 3.5, duration: 0.3, velocity: 65 });
      });
    }
  });
  return humanize(notes, BPM, "tight");
}
