// Sketch: "Midnight Transit on Wacker"
// Vibe: Detroit-meets-Philly soul. Driving, warm, and rhythmic with a Chicago urban edge.
// BPM: 122 | Key: F Minor | Bars: 16 | Humanize: loose
//
// Generated by Unkle Funk Dream Engine — 2026-09-30

import type { NoteDescription } from "@ableton-extensions/sdk";
import { humanize } from "../humanizer.js";

export const SKETCH_NAME = "Midnight Transit on Wacker";
export const BPM = 122;
export const BARS = 16;
export const KEY = "F Minor";

// Trigger note for all drum tracks (separate-track setup, C3 = 48)
const TRIGGER = 48;
const BEATS = BARS * 4;

// Bass pitches in F minor (MIDI, C2 register)
const F1  = 29;
const Ab1 = 32;
const C2  = 36;
const Eb2 = 39;
const F2  = 41;

// Chord pitches: Fm7 (Ab4, C5, Eb5, F5)
const Ab4 = 56;
const C5  = 60;
const Eb5 = 63;
const F5  = 65;

// ─── Kick: Steady 4/4 with slight velocity swing ──────────────────────────
export function kickNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    for (let beat = 0; beat < 4; beat++) {
      notes.push({
        pitch: TRIGGER,
        startTime: barStart + beat,
        duration: 0.3,
        velocity: beat === 0 ? 110 : 100
      });
    }
  }
  return humanize(notes, BPM, "loose");
}

// ─── Snare: Deep 2 and 4 ──────────────────────────────────────────────────
export function snareNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Standard 2 and 4
    notes.push({ pitch: TRIGGER, startTime: barStart + 1, duration: 0.25, velocity: 105 });
    notes.push({ pitch: TRIGGER, startTime: barStart + 3, duration: 0.25, velocity: 105 });
  }
  return humanize(notes, BPM, "loose");
}

// ─── Hi-Hats: 16th note Detroit shuffle ───────────────────────────────────
export function hatNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    for (let i = 0; i < 16; i++) {
      const beat = i * 0.25;
      // Accents on the 8th notes to drive the shuffle
      const isAccent = i % 2 === 0;
      notes.push({
        pitch: TRIGGER,
        startTime: barStart + beat,
        duration: 0.1,
        velocity: isAccent ? 85 : 60
      });
    }
  }
  return humanize(notes, BPM, "loose");
}

// ─── Percs: Rim shot accents on the "and" of 4 ────────────────────────────
export function percNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Rim shot on the upbeat of 4
    notes.push({
      pitch: TRIGGER,
      startTime: barStart + 3.5,
      duration: 0.15,
      velocity: 75
    });
  }
  return humanize(notes, BPM, "loose");
}

// ─── Bass: Syncopated F minor groove ──────────────────────────────────────
export function bassNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  const pattern = [
    { b: 0, p: F1, d: 0.5, v: 100 },
    { b: 0.75, p: F1, d: 0.25, v: 85 },
    { b: 1.5, p: Ab1, d: 0.5, v: 90 },
    { b: 2.25, p: Eb2, d: 0.5, v: 95 },
    { b: 3, p: C2, d: 1.0, v: 88 },
  ];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    pattern.forEach(note => {
      notes.push({
        pitch: note.p,
        startTime: barStart + note.b,
        duration: note.d,
        velocity: note.v
      });
    });
  }
  return humanize(notes, BPM, "loose");
}

// ─── Chords: Lush Fm7 stabs ───────────────────────────────────────────────
export function chordNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  const chord = [Ab4, C5, Eb5, F5];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Stab on the "and" of 2 and the "and" of 4 (syncopated soul placement)
    const stabTimes = [2.5, 3.5];
    
    // Only stab on certain bars to create movement
    if (bar % 2 === 0) {
      stabTimes.forEach(t => {
        chord.forEach(p => {
          notes.push({ pitch: p, startTime: barStart + t, duration: 0.4, velocity: 70 });
        });
      });
    }
  }
  return humanize(notes, BPM, "loose");
}