// Sketch: "Wicker Park After Hours"
// Vibe: Warm, soulful, jazzy deep house. Wicker Park late-night lounge energy.
// BPM: 122 | Key: F# Minor | Bars: 16 | Humanize: loose (percs), tight (others)
//
// Generated by Unkle Funk Dream Engine — 2026-10-04

import type { NoteDescription } from "@ableton-extensions/sdk";
import { humanize } from "../humanizer.js";

export const SKETCH_NAME = "Wicker Park After Hours";
export const BPM = 122;
export const BARS = 16;
export const KEY = "F# Minor";

// Trigger note for all drum tracks (separate-track setup, C3 = 48)
const TRIGGER = 48;

// Bass pitches in F# minor (MIDI, C2 register range)
const BASS_FSH = 30; // F#1
const BASS_A = 33;   // A1
const BASS_B = 34;   // B1
const BASS_CS = 36;  // C#2

// Chord pitches: F#m7 = F#4, A4, C#5, E5
const CHORD_FSH = 66;
const CHORD_A = 69;
const CHORD_CS = 73;
const CHORD_E = 76;

// ─── Kick: standard 4/4 with a slight syncopated ghost kick ────────────────
export function kickNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Downbeats
    notes.push({ pitch: TRIGGER, startTime: barStart, duration: 0.4, velocity: 110 });
    notes.push({ pitch: TRIGGER, startTime: barStart + 2, duration: 0.4, velocity: 105 });
    
    // Ghost kick on the 16th note before beat 3 in every 4th bar
    if (bar % 4 === 3) {
      notes.push({ pitch: TRIGGER, startTime: barStart + 1.75, duration: 0.2, velocity: 75 });
    }
  }
  return humanize(notes, BPM, "tight");
}

// ─── Snare: 2 and 4 ───────────────────────────────────────────────────────
export function snareNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    // Beat 2 (index 1) and Beat 4 (index 3)
    notes.push({ pitch: TRIGGER, startTime: barStart + 1, duration: 0.2, velocity: 95 });
    notes.push({ pitch: TRIGGER, startTime: barStart + 3, duration: 0.2, velocity: 95 });
  }
  return humanize(notes, BPM, "tight");
}

// ─── Hi-Hats: Driving 16th notes ──────────────────────────────────────────
export function hatNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    for (let i = 0; i < 16; i++) {
      const stepTime = i * 0.25;
      // Vary velocity for a natural shuffle
      const vel = i % 2 === 0 ? 70 : 85;
      notes.push({ pitch: TRIGGER, startTime: barStart + stepTime, duration: 0.1, velocity: vel });
    }
  }
  return humanize(notes, BPM, "tight");
}

// ─── Percs: Bongo-style syncopation ───────────────────────────────────────
export function percNotes(): NoteDescription[] {
  const notes: NoteDescription[] = [];
  // Syncopated pattern: 1.25, 2.5, 3.75
  const pattern = [
    { beat: 1.25, vel: 75, dur: 0.15 },
    { beat: 2.5,  vel: 85, dur: 0.15 },
    { beat: 3.75, vel: 70, dur: 0.15 },
  ];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    pattern.forEach(({ beat, vel, dur }) => {
      notes.push({ pitch: TRIGGER, startTime: barStart + beat, duration: dur, velocity: vel });
    });
  }
  return humanize(notes, BPM, "loose");
}

// ─── Bass: F#m rhythmic groove ────────────────────────────────────────────
export function bassNotes(): NoteDescription[] {
  const pattern: NoteDescription[] = [];
  
  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;
    
    // Basic rhythmic motif
    if (bar % 2 === 0) {
      // Bar A: Root and Fifth
      pattern.push({ pitch: BASS_FSH, startTime: barStart, duration: 0.5, velocity: 100 });
      pattern.push({ pitch: BASS_FSH, startTime: barStart + 1.5, duration: 0.5, velocity: 90 });
      pattern.push({ pitch: BASS_CS, startTime: barStart + 2.5, duration: 1.0, velocity: 85 });
    } else {
      // Bar B: Root and Third/Sixth feel
      pattern.push({ pitch: BASS_FSH, startTime: barStart, duration: 0.5, velocity: 100 });
      pattern.push({ pitch: BASS_A,   startTime: barStart + 1.5, duration: 0.5, velocity: 90 });
      pattern.push({ pitch: BASS_B,   startTime: barStart + 3, duration: 0.8, velocity: 85 });
    }
  }
  return humanize(pattern, BPM, "tight");
}

// ─── Chords: F#m7 jazzy stabs ─────────────────────────────────────────────
export function chordNotes(): NoteDescription[] {
  const chord = [CHORD_FSH, CHORD_A, CHORD_CS, CHORD_E];
  const notes: NoteDescription[] = [];

  for (let bar = 0; bar < BARS; bar++) {
    const barStart = bar * 4;

    // Stab on the 'and' of 1 (beat 0.5)
    chord.forEach(p => {
      notes.push({ pitch: p, startTime: barStart + 0.5, duration: 0.4, velocity: 75 });
    });

    // Call and response: Stab on beat 3.5 every 2nd bar
    if (bar % 2 === 1) {
      chord.forEach(p => {
        notes.push({ pitch: p, startTime: barStart + 3.5, duration: 0.3, velocity: 65 });
      });
    }
  }
  return humanize(notes, BPM, "tight");
}